sudo: required
dist: trusty

notifications:
  email:
    recipients:
      - david.peicho@gmail.com
    on_success: never
    on_failure: always

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
 
language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - cmake
            - libgtest-dev
script:
  - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-5 /usr/bin/g++
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp /usr/src/gtest/*.a /usr/lib
  - cd -
  - export CXX=$COMPILER; 
  - mkdir build; cd build/; cmake ..; make check
  - cd bin && ./check
